### ISSUE TITLE
Support 6-pin Joystick

### ISSUE THREAD

**Issue by craigmillard86** [sfraint/wireless-n64-controller#8]
Hi There,

Great project! I have the PCB and ESP32 setup, but I just realised my analogue stick is a 6-pin version, not the 4pin like the board has been designed. From what I can tell the 6-pin is the standard type.

This pinout is like this https://dpedu.io/article/2015-03-11/nintendo-64-joystick-pinout-arduino

Im looking at how to modify the code to support but do you have any ideas about where to start? 
get_analog_raw looks promising but not sure how to bring the other pin into it..

Thanks

**Comment by sfraint** [comment]
Interesting. All of the USB controllers I've seen had 4-pin joystick cables. Does your controller have an N64 plug instead of USB? And is it an original controller or a repro?

If it is a repro, it might still use a 2-axis potentiometer which you can easily convert to 4-pin. Later this week I can try to dig up some pictures of a 6-pin to 4-pin "conversion" I did for a potentiometer based joystick.

**Comment by craigmillard86** [comment]
Ah, that might be it, I am looking to convert my original OEM N64 controllers, everything else looks the same apart from the joystick. Looking to save some controllers from landfill:)

After a bit of research, the OEM 6pin sticks use two linear sensors and are not true analog as with the repro ones in the USB controllers.:
_The analog stick uses a pair of optical encoding disks to determine its relative position. This works similarly to linear encoders found in printers, except that instead of being a strip of tape/film, the N64 uses a rotating disk for each axis. Each disk has small holes along the circumference of the disk. These holes allow light to pass through to an optical sensor on the opposite side.

When the stick is moved, there are two signals generated per axis, for a total of four, which are slightly offset from each other. One of the two signals is used as the interrupt signal (XA and YA for the x-axis and y-axis respectively), and the other (XB and YB) is compared with the state of the first in order to determine which direction (positive or negative) that analog stick is moving for that axis.

To determine the direction along a particular axis and how far the stick has moved, the NUS-CNT chip will listen for any changing edge of that axis' interrupt signal (e.g. XA for the x-axis). A changing edge means any time the signal goes from LOW to HIGH, or HIGH to LOW. When an edge change is detected, the state of XA is compared against XB. If input, then the stick has moved +1 units. If input, then the stick has moved -1 units. While the analog stick reports relative movement whenever it moves, the N64 console requires the current position, not relative. In order to provide that, the NUS-CNT chip keeps track of these movements. The initial values for each axis is zero._

I am thinking something like this, y axis only here for an example (would duplicate for x axis):
```
int16_t county = 0;

int16_t analogy_to_combined_value() {
    int16_t rawa = gpio_get_level(ANALOG_Y);
    int16_t rawb = gpio_get_level(ANALOG_Yb);
  if(rawa == rawb) {
    county++;
  }
  else{
    county--;
  }
  int32_t yaxis = (county * 365); //scale by factor of 365 as n64 sensors range from -90 -> +90
  return (analog_to_joystick_value(yaxis, min_y, center_y, max_y))
}
```
This will replace the get_analog_raw function when polling for the joystick. Not sure how this will interact with analog_to_joystick_value map functions.. 

Any thoughts on this so far, love to get your advice on this?

**Comment by sfraint** [comment]
I'll have to read up a bit more, but two things come to mind so far:
1. You're going to need 4 sensor pins from the ESP32, not just the two that are already dedicated to the joystick. And you'll need to connect these somehow since the PCB only has two traces for the joystick signals 
    * Or you could add hardware to convert the encoder signal into analog signals for the ESP32, but this doesn't seem worth it in my opinion 
1. Seems like you will need to use [interrupts](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/gpio/generic_gpio) to detect `XA` and `YA` changes instead of monitoring this in the poll loop

**Comment by craigmillard86** [comment]
Thanks! I have a test project working with interrupts and the additional Pins (13,35) via the PCB :) 

I will take a look at embedding this into the project on my fork, making it optional, 4-pin or 6-pin.

**Comment by craigmillard86** [comment]
First cut is on branch here:
https://github.com/craigmillard86/wireless-n64-controller/tree/6pin-n64

**Comment by sfraint** [comment]
Very cool! Glad you were able to make this work!

This seems like a great feature to add back to this repo if you want to send a Pull Request 😁 That might take a little more work but hopefully it's not too bad (e.g. to update or disable calibration)

**Comment by craigmillard86** [comment]
I have updated it to include Calibration, which required a refactor but all good now!

I have raised a PR [here](https://github.com/sfraint/wireless-n64-controller/pull/9) let me know your thoughts

**Comment by sfraint** [comment]
Thank you! I will try to take a look and try this out this weekend

**Comment by sfraint** [comment]
Support for 6-pin style joysticks was added in https://github.com/sfraint/wireless-n64-controller/pull/9

Thanks again @craigmillard86!
